### PR TITLE
feat: add filtered adapter(#3)

### LINKED ISSUE #3: Support policy subset loading
https://casbin.org/docs/en/policy-subset-loading

I can submit a PR for this if you're open to reviewing one.

### PR DESCRIPTION
**Pull request by kilosonc**
Signed-off-by: closetool <c299999999@qq.com>

FIX: #3

### CODE REVIEW

**Comment by hsluoyz** [comment]
@fgblomqvist please review.

**Review by fgblomqvist — APPROVED** [review]
Looks good to me, thanks

**Comment by hsluoyz** [comment]
@cychiuae please review.

**Comment by hsluoyz** [comment]
We also forked this repo in case the owner is not active. @closetool you can also send this PR here: https://github.com/casbin/casbin-pg-adapter

**Comment by hsluoyz** [comment]
@closetool plz separate the branch for this PR and the branch for repo: https://github.com/casbin/casbin-pg-adapter . Currently this PR is already polluted. Plz restore the branch in this PR to its initial state so the owner of this repo can review it. You can use another branch for repo: https://github.com/casbin/casbin-pg-adapter

**Comment by cychiuae** [comment]
Thanks!

**Pull request merged**
