### PR TITLE
add travis and github action ci

### PR DESCRIPTION
**Pull request by kilosonc**
Signed-off-by: closetool <c299999999@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@cychiuae @fgblomqvist plz review.

**Review by fgblomqvist — APPROVED** [review]

**Comment by fgblomqvist** [comment]
Any update on this one? @cychiuae

**Comment by fgblomqvist** [comment]
Bump @cychiuae

**Comment by hsluoyz** [comment]
@cychiuae

**Pull request closed without merging**
